### ISSUE TITLE
ACDC数据预处理

### ISSUE THREAD

**Issue by hu1231233** [kingo233/FCT-Pytorch#2]
运行shutil.copy(d, join(out_folder, "imagesTr", patient_identifier + ".nii.gz"))这句代码的时候
报错 FileNotFoundError: [Errno 2] No such file or directory: 'Task027_ACDC\\imagesTr\\training\\patient001\\patient001_frame01.nii.gz'

提前在Task027_ACDC创建好文件，才不会出现这种错误，但100多个病人的数据，总不能一个一个创建吧，作者有解决的方法吗

**Comment by kingo233** [comment]
这里忘了解释一下了，acdc_processing.py这个文件原本是为了配合monai框架的数据读入和预处理准备的。但是目前的代码其实不需要这个acdc_processing.py，把数据集下载下来之后，删除里面的.md文件就可以直接运行了。

The acdc_processing.py file was originally designed to work with the monai framework for data input and preprocessing. However, the current code does not require this file. After downloading the dataset, you can directly run it by deleting the .md files inside.

**Comment by hu1231233** [comment]
作者回答迅速，谢谢作者的回复

**Comment by Susu0812** [comment]
> 运行shutil.copy（d， join（out_folder， “imagesTr”， patient_identifier + “.nii.gz”））这句代码的时候 报错 FileNotFoundError： [Errno 2] No such file or directory： 'Task027_ACDC\imagesTr\training\patient001\patient001_frame01.nii.gz'
> 
> 提前在Task027_ACDC创建好文件，才不会出现这种错误，但100多个病人的数据，总不能一个创建吧，作者有解决的方法吗

你好，请问你复现成功了吗，我在复现的过程遇到了一些问题，是否方便交流讨论一下呢
