### ISSUE TITLE
Can you tell me the environment setting version and data set configuration

### ISSUE THREAD

**Issue by jgdxg** [kingo233/FCT-Pytorch#4]

**Comment by kingo233** [comment]
是要reqirements.txt 和 什么？

**Comment by jgdxg** [comment]
就我下载了acdc的数据集后，先运行了acdc_processing.py文件，不是把文件划分为imagesTr和labelsTs然后运行main.py文件的数据路径输入那点没太明白输入的是什么

**Comment by kingo233** [comment]
please refer https://github.com/kingo233/FCT-Pytorch/issues/2

**Comment by jgdxg** [comment]
好的，谢谢。可以给一下reqirements.txt吗

**Comment by kingo233** [comment]
你可以建一个新的conda环境，然后不断python main.py看看缺哪些库，缺啥装啥。我自己的环境已经删除了，最近在做别的事，很抱歉不能立即提供。
